version: '2'

volumes:
  orderer.qrneo-network.com:
  peer0.taguig.qrneo-network.com:
  peer1.taguig.qrneo-network.com:
  peer0.magsaysay.qrneo-network.com:
  peer1.magsaysay.qrneo-network.com:

networks:
  byfn:

services:

  orderer.qrneo-network.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.qrneo-network.com
    container_name: orderer.qrneo-network.com
    networks:
      - byfn

  peer0.taguig.qrneo-network.com:
    container_name: peer0.taguig.qrneo-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.taguig.qrneo-network.com
    networks:
      - byfn

  peer1.taguig.qrneo-network.com:
    container_name: peer1.taguig.qrneo-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.taguig.qrneo-network.com
    networks:
      - byfn

  peer0.magsaysay.qrneo-network.com:
    container_name: peer0.magsaysay.qrneo-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.magsaysay.qrneo-network.com
    networks:
      - byfn

  peer1.magsaysay.qrneo-network.com:
    container_name: peer1.magsaysay.qrneo-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.magsaysay.qrneo-network.com
    networks:
      - byfn

  qrneocli:
    container_name: qrneocli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=qrneocli
      - CORE_PEER_ADDRESS=peer0.taguig.qrneo-network.com:7051
      - CORE_PEER_LOCALMSPID=TaguigMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/taguig.qrneo-network.com/peers/peer0.taguig.qrneo-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/taguig.qrneo-network.com/peers/peer0.taguig.qrneo-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/taguig.qrneo-network.com/peers/peer0.taguig.qrneo-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/taguig.qrneo-network.com/users/Admin@taguig.qrneo-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.qrneo-network.com
      - peer0.taguig.qrneo-network.com
      - peer1.taguig.qrneo-network.com
      - peer0.magsaysay.qrneo-network.com
      - peer1.magsaysay.qrneo-network.com
    networks:
      - byfn